-- Renames the 'print' API-key permission to 'jobs:submit'.
--
-- Data only: `api_key_permissions.permission` is a plain TEXT column against the closed set in
-- lib/domain/permissions.ts, so nothing about the schema changes. What does change is that
-- `parseStoredPermissions` no longer recognises 'print' — an unknown grant is dropped rather than
-- honoured — so without this every existing key would silently stop being able to print.
--
-- The composite primary key is (api_key_id, permission), so a key already holding both rows would
-- collide on the update. `OR REPLACE` resolves that by keeping the one row the pair collapses to,
-- which is the correct result: they name the same grant.
UPDATE OR REPLACE "api_key_permissions" SET "permission" = 'jobs:submit' WHERE "permission" = 'print';
